### ISSUE TITLE
Slides with non integer widths result in previous/next slide's content leaking in the current slide

### ISSUE THREAD

**Issue by dumptyd** [mpbarlow/vue-renderless-carousel#2]
The white part in the image is from the previous slide. Depending on whether the slide width's decimal value is greater or smaller than 0.5, it results in next and previous slide's content leaking in, respectively. 

I think it has to do with this line https://github.com/mpbarlow/vue-renderless-carousel/blob/44dfaf71c3091881ba6621a1270d5a99713f86da/src/RlCarousel.vue#L126 as clientHeight and clientWidth return the rounded value. Replacing that with `getBoundingClientRect().width/height` should fix the issue.

![image](https://user-images.githubusercontent.com/16368429/95029422-bb8f8080-06c5-11eb-927e-1279689e8462.png)

**Comment by mpbarlow** [comment]
Thank you for the report! I will make sure it's fixed in the next release.
