### ISSUE TITLE
Carousel not responding to slideIndex update after 1.3.0 update

### ISSUE THREAD

**Issue by silvaDominic** [mpbarlow/vue-renderless-carousel#4]
Looks like we've already got something haha. This is a strange and small issue, but the view/carousel is not responding to the update made in the nextTick function as it was before the update.

```
    addListItem() {
      this.items.push(new Item());
      
      this.$nextTick(() => {
        this.slideIndex = this.items.length - 1;
      });
    },
```

This just slides to the newest slide added. This can be remedied with this common hack:

```
    addListItem() {
      this.items.push(new Item());
      
      setTimeout(() => {
        this.slideIndex = this.items.length - 1;
      }, 0);
    },
```
My setup is crude and based off of one of your examples.
I can't quite tell if this is a result of your changes in the mounted hook or a Vue issue caused by the dependency update. As I said, I _can_ get around it pretty harmlessly for now, but clearly something is up, however small.

**Comment by mpbarlow** [comment]
Hmm, sorry about this, I’ll take a look after work.

I’m guessing it doesn’t work if you remove the nextTick/setTimeout entirely and just have the slideIndex update immediately? 

One of the changes I made was to wrap the internal width recalculation in nextTick when a slide was added/removed, with the intent to prevent exactly this sort of problem!

**Comment by silvaDominic** [comment]
Correct, it does not update without either. That's exactly why I originally used nextTick...So I just did a quick check and removed the nextTick in your code and got it working again with nextTick in my component.

I did some very crude testing with the 3 different ways to update the slide index with the current production build and got these results:

```
     this.items.push(new Item());
     this.slideIndex = this.items.length - 1; 
```
This executes first in my comp, then the nextTick in RLCar

```
    addListItem() {
      this.items.push(new Item());
      
      this.$nextTick(() => {
        this.slideIndex = this.items.length - 1;
      });
    },
```
This _also_ executes first in my comp, then the nextTick in RLCar

```
    addListItem() {
      this.items.push(new Item());
      
      setTimeout(() => {
        this.slideIndex = this.items.length - 1;
      }, 0);
    },
```
nextTick in RLCar executes first and _then_ this in my comp. **This is the one that works.**

So it appears as though your nextTick function is executing too late in the desired usecases.

**Comment by mpbarlow** [comment]
Yep, that serves me right for trying to fix problems that didn't exist! Thanks for investigating.

I've reverted the nextTick call in 1.3.1, can you let me know if that's working as expected now?

**Comment by silvaDominic** [comment]
Just did a fresh install of dependencies and it appears to be working as before!

Can't thank you enough for taking the time to update the repo and remove any doubts. It's literally the only carousel plugin I could get working in my project.

Cheers

**Comment by mpbarlow** [comment]
You’re very welcome, I’m glad the project has been useful 😀
